{% set version = "3.54.0" %}
{% set year = "2026" %}
{% set version_split = version.split(".") %}
{% set major = version_split[0] %}
{% set minor = version_split[1]|int * 10 %}
{% set bugfix = version_split[2]|int * 100 %}
{% set version_coded=(major ~ (("%03d" % minor)|string) ~ (("%03d" % bugfix)|string)) %}

package:
  name: sqlite-tools
  version: {{ version }}

source:
  url: https://www.sqlite.org/{{ year }}/sqlite-src-{{ version_coded }}.zip
  sha256: 8847659821e0c5116bd14a94644c82ba932b2d9a05ac81af2e34af814aad7c58

build:
  skip: true  # [win and arm64]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [not win]
    - tcl >=9
  host:
    - libsqlite >={{ version }}  # [not win]
    - zlib                       # [not win]
    - tcl >=9

outputs:
  - name: dbhash
    files:
      - bin/dbhash              # [unix]
      - Library\bin\dbhash.exe  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make  # [not win]
      host:
        - libsqlite >={{ version }}  # [not win]
        - zlib                       # [not win]

    test:
      commands:
        - dbhash --help
  - name: sqldiff
    files:
      - bin/sqldiff              # [unix]
      - Library\bin\sqldiff.exe  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make  # [not win]
      host:
        - libsqlite >={{ version }}  # [not win]
        - zlib                       # [not win]

    test:
      commands:
        - sqldiff --help
  - name: sqlite_rsync
    files:
      - bin/sqlite3_rsync              # [unix]
      - Library\bin\sqlite3_rsync.exe  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make  # [not win]
      host:
        - libsqlite >={{ version }}  # [not win]
        - zlib                       # [not win]

    test:
      commands:
        - sqlite3_rsync --version


about:
  home: http://www.sqlite.org/
  license: blessing
  license_url: http://www.sqlite.org/copyright.html
  summary: C library that implements an SQL database engine
  description: |
    SQLite is a small, fast, serverless SQL database engine. Programs that
    link with this library get SQL database access without running a
    separate RDBMS process.
  doc_url: http://www.sqlite.org/docs.html
  doc_source_url: https://www.sqlite.org/src/dir?ci=trunk&name=doc
  dev_url: https://www.sqlite.org/src/dir?ci=trunk

extra:
  feedstock-name: sqlite-tools
  recipe-maintainers:
    - flaviomartins
